CHANNELS = ["@TheBoysinTelegram"]

movies = {

# VIDEO 1-30
"film1": {"type": "video", "file_id": "..."},
"film2": {"type": "video", "file_id": "..."},
"film3": {"type": "video", "file_id": "..."},
"film4": {"type": "video", "file_id": "..."},
"film5": {"type": "video", "file_id": "..."},
"film6": {"type": "video", "file_id": "..."},
"film7": {"type": "video", "file_id": "..."},
"film8": {"type": "video", "file_id": "..."},
"film9": {"type": "video", "file_id": "..."},
"film10": {"type": "video", "file_id": "..."},
"film11": {"type": "video", "file_id": "..."},
"film12": {"type": "video", "file_id": "..."},
"film13": {"type": "video", "file_id": "..."},
"film14": {"type": "video", "file_id": "..."},
"film15": {"type": "video", "file_id": "..."},
"film16": {"type": "video", "file_id": "..."},
"film17": {"type": "video", "file_id": "..."},
"film18": {"type": "video", "file_id": "..."},
"film19": {"type": "video", "file_id": "..."},
"film20": {"type": "video", "file_id": "..."},
"film21": {"type": "video", "file_id": "..."},
"film22": {"type": "video", "file_id": "..."},
"film23": {"type": "video", "file_id": "..."},
"film24": {"type": "video", "file_id": "..."},
"film25": {"type": "video", "file_id": "..."},
"film26": {"type": "video", "file_id": "..."},
"film27": {"type": "video", "file_id": "..."},
"film28": {"type": "video", "file_id": "..."},
"film29": {"type": "video", "file_id": "..."},
"film30": {"type": "video", "file_id": "..."},

# PHOTO 1-30
"photo1": {"type": "photo", "AgACAgQAAxkBAAMWajkmex95oJF1P7f-5HzMaW43OB8AAgwVaxuDoslRq_IfDHVL4V0BAAMCAAN4AAM8BA": "..."},
"photo2": {"type": "photo", "file_id": "..."},
"photo3": {"type": "photo", "file_id": "..."},
"photo4": {"type": "photo", "file_id": "..."},
"photo5": {"type": "photo", "file_id": "..."},
"photo6": {"type": "photo", "file_id": "..."},
"photo7": {"type": "photo", "file_id": "..."},
"photo8": {"type": "photo", "file_id": "..."},
"photo9": {"type": "photo", "file_id": "..."},
"photo10": {"type": "photo", "file_id": "..."},
"photo11": {"type": "photo", "file_id": "..."},
"photo12": {"type": "photo", "file_id": "..."},
"photo13": {"type": "photo", "file_id": "..."},
"photo14": {"type": "photo", "file_id": "..."},
"photo15": {"type": "photo", "file_id": "..."},
"photo16": {"type": "photo", "file_id": "..."},
"photo17": {"type": "photo", "file_id": "..."},
"photo18": {"type": "photo", "file_id": "..."},
"photo19": {"type": "photo", "file_id": "..."},
"photo20": {"type": "photo", "file_id": "..."},
"photo21": {"type": "photo", "file_id": "..."},
"photo22": {"type": "photo", "file_id": "..."},
"photo23": {"type": "photo", "file_id": "..."},
"photo24": {"type": "photo", "file_id": "..."},
"photo25": {"type": "photo", "file_id": "..."},
"photo26": {"type": "photo", "file_id": "..."},
"photo27": {"type": "photo", "file_id": "..."},
"photo28": {"type": "photo", "file_id": "..."},
"photo29": {"type": "photo", "file_id": "..."},
"photo30": {"type": "photo", "file_id": "..."},

# AUDIO 1-30
"audio1": {"type": "audio", "file_id": "..."},
"audio2": {"type": "audio", "file_id": "..."},
"audio3": {"type": "audio", "file_id": "..."},
"audio4": {"type": "audio", "file_id": "..."},
"audio5": {"type": "audio", "file_id": "..."},
"audio6": {"type": "audio", "file_id": "..."},
"audio7": {"type": "audio", "file_id": "..."},
"audio8": {"type": "audio", "file_id": "..."},
"audio9": {"type": "audio", "file_id": "..."},
"audio10": {"type": "audio", "file_id": "..."},
"audio11": {"type": "audio", "file_id": "..."},
"audio12": {"type": "audio", "file_id": "..."},
"audio13": {"type": "audio", "file_id": "..."},
"audio14": {"type": "audio", "file_id": "..."},
"audio15": {"type": "audio", "file_id": "..."},
"audio16": {"type": "audio", "file_id": "..."},
"audio17": {"type": "audio", "file_id": "..."},
"audio18": {"type": "audio", "file_id": "..."},
"audio19": {"type": "audio", "file_id": "..."},
"audio20": {"type": "audio", "file_id": "..."},
"audio21": {"type": "audio", "file_id": "..."},
"audio22": {"type": "audio", "file_id": "..."},
"audio23": {"type": "audio", "file_id": "..."},
"audio24": {"type": "audio", "file_id": "..."},
"audio25": {"type": "audio", "file_id": "..."},
"audio26": {"type": "audio", "file_id": "..."},
"audio27": {"type": "audio", "file_id": "..."},
"audio28": {"type": "audio", "file_id": "..."},
"audio29": {"type": "audio", "file_id": "..."},
"audio30": {"type": "audio", "file_id": "..."},

# DOCUMENT 1-30
"document1": {"type": "document", "file_id": "..."},
"document2": {"type": "document", "file_id": "..."},
"document3": {"type": "document", "file_id": "..."},
"document4": {"type": "document", "file_id": "..."},
"document5": {"type": "document", "file_id": "..."},
"document6": {"type": "document", "file_id": "..."},
"document7": {"type": "document", "file_id": "..."},
"document8": {"type": "document", "file_id": "..."},
"document9": {"type": "document", "file_id": "..."},
"document10": {"type": "document", "file_id": "..."},
"document11": {"type": "document", "file_id": "..."},
"document12": {"type": "document", "file_id": "..."},
"document13": {"type": "document", "file_id": "..."},
"document14": {"type": "document", "file_id": "..."},
"document15": {"type": "document", "file_id": "..."},
"document16": {"type": "document", "file_id": "..."},
"document17": {"type": "document", "file_id": "..."},
"document18": {"type": "document", "file_id": "..."},
"document19": {"type": "document", "file_id": "..."},
"document20": {"type": "document", "file_id": "..."},
"document21": {"type": "document", "file_id": "..."},
"document22": {"type": "document", "file_id": "..."},
"document23": {"type": "document", "file_id": "..."},
"document24": {"type": "document", "file_id": "..."},
"document25": {"type": "document", "file_id": "..."},
"document26": {"type": "document", "file_id": "..."},
"document27": {"type": "document", "file_id": "..."},
"document28": {"type": "document", "file_id": "..."},
"document29": {"type": "document", "file_id": "..."},
"document30": {"type": "document", "file_id": "..."}

}
